stages:
  - build
  - deploy
  - clear

build:
  stage: build
  tags:
    - academy
  script:
    - cp ./deploy/.env.example .env.deploy
    - cp ./deploy/docker-compose.deploy.yml docker-compose.deploy.yml
    - cp ./deploy/Dockerfile Dockerfile
    - docker compose -f docker-compose.deploy.yml --env-file .env.deploy build
  artifacts:
    paths:
      - .env.deploy
      - docker-compose.deploy.yml
      - Dockerfile

deploy:
  stage: deploy
  tags:
    - academy
  script:
    - docker compose --env-file .env.deploy -f docker-compose.deploy.yml up -d --force-recreate --remove-orphans
    - docker compose --env-file .env.deploy -f docker-compose.deploy.yml exec app php artisan migrate --force

clear:
  stage: clear
  tags:
    - academy
  script:
    - docker system prune --all --force
