version: "3.7"
services:
  app:
    build:
      context: ./docker/backend
      target: backend
    image: productivity
    container_name: productivity-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - productivity
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: mysql:5.7
    container_name: productivity-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./backend/docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - productivity

  docs:
    image: registry.hub.docker.com/swaggerapi/swagger-ui:v4.17.0
    restart: always
    environment:
      SWAGGER_JSON_URL: /docs/openapi.yaml
      BASE_URL: /docs
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: /docs
      LETSENCRYPT_HOST: localhost
    volumes:
      - ./backend/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    networks:
      - productivity

  nginx:
    build:
      context: ./docker/backend
      target: nginx
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: localhost
      VIRTUAL_PATH: /
      LETSENCRYPT_HOST: localhost
    restart: always
    depends_on:
      - app
    networks:
      - productivity

networks:
  productivity:
    driver: bridge
