version: "3.7"
services:
  app:
    env_file: ".env"
    build:
      context: .
      target: backend
      dockerfile: Dockerfile
    links:
      - db
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - productivity

  db:
    env_file:
      - ./.env
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - ./docker/backend/mysql/:/var/lib/mysql
    networks:
      - productivity

  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: always
    networks:
      - productivity

  docs:
    image: registry.hub.docker.com/swaggerapi/swagger-ui:v4.17.0
    restart: always
    ports:
      - "8888:8080"
    environment:
      SWAGGER_JSON_URL: /openapi.yaml
    volumes:
      - ./backend/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    networks:
      - productivity

networks:
  productivity:
    driver: bridge
