version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: docker/backend/
      dockerfile: Dockerfile
    image: productivity
    # container_name: productivity-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - productivity
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: mysql:5.7
    # container_name: productivity-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./backend/docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - productivity
      
  nginx:
    image: nginx:1.17-alpine
    # container_name: productivity-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - productivity

networks:
  productivity:
    driver: bridge
